/**
 * Referenced from	Derek Molloy	http://www.derekmolloy.ie/
 * @brief  A Linux user space program that communicates with the randnum_char.c LKM. 
 * It reads a random number generated by the LKM randnumchar.
 */

#include<stdio.h>
#include<errno.h>
#include<fcntl.h>
#include<unistd.h>

int main(){
	int ret, fd;
	   
	printf("Starting device test code example...\n");
	fd = open("/dev/randnumchar", O_RDWR);             // Open the device with read/write access
	if (fd < 0){
		perror("Failed to open the device...");
		return errno;
	}
  
	unsigned int randnum;
	printf("Reading from the device...\n");
	ret = read(fd, &randnum, sizeof(unsigned int));        // Read the random number from the LKM
	if (ret < 0){
		perror("Failed to read the message from the device.");
	return errno;
	}
	printf("The received random number is: %u\n", randnum);
	
	printf("End of the program\n");
	return 0;
}
